services:
  postgres:
    image: postgres:16.14-alpine3.24
    ports:
      - "5432:5432"

    environment:
      POSTGRES_DB: cv_db
      POSTGRES_USER: cv_crafter
      POSTGRES_PASSWORD: cv_crafter_password
  
  redis:
    image: redis:7-alpine
    ports: 
      - "6379:6379"

  django:
    build: 
      context: ./backend
    ports:
      - "8000:8000"

    depends_on:
      - postgres
      - redis